name: fail-skip-test
version: 1.0.0
jobs:
  job-a:
    runtime: alpine:3.18
    steps:
      - name: fail
        run: "echo 'About to fail' && exit 1"
  job-b:
    runtime: alpine:3.18
    needs: [job-a]
    steps:
      - name: should-skip
        run: "echo 'This should never run'"
